name: release

on:
    push:
        branches:
        - main

jobs:
  docker:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
            load: true
            tags: netfoundry/ziti-k8s-agent:test
      - 
        name: Get version from container
        run: echo "version=`docker run --rm netfoundry/ziti-k8s-agent:test version`" >> $GITHUB_OUTPUT
        id: version
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: netfoundry/ziti-k8s-agent:${{steps.version.outputs.version}},netfoundry/ziti-k8s-agent:latest
